### ISSUE TITLE
[Question] `artifacts.loop()` deals actual road loops, not iteration

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#100]
The [`artifacts.loop()`](https://github.com/uscuni/sgeop/blob/8e10d48cf1197e945dc210bc721c9e0c6f974ea1/sgeop/artifacts.py#L473) function deals with geometric/road loops, correct? (nothing to do with the [`simplify.simplify_loop()`](https://github.com/uscuni/sgeop/blob/8e10d48cf1197e945dc210bc721c9e0c6f974ea1/sgeop/simplify.py#L574) function, correct?)

@martinfleis Can yon confirm this?

**Comment by martinfleis** [comment]
This deals with loops composed of continuity strokes. Different concept.

**Comment by jGaboardi** [comment]
Ah, OK. So this is something like multiple `C` strokes that combine into a loop structure?

**Comment by martinfleis** [comment]
Yeah. Something like that, but possibly E? Would have to spend more time looking.
