### ISSUE TITLE
[Question] commented out `buffer` keyword in `artifacts.n1_g1_identical()`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#108]
We have the commented out [`buffer` keyword](https://github.com/uscuni/sgeop/blob/2a5d6eba1f560c7dec36e0fbbfa91655c31cb086/sgeop/artifacts.py#L665) in `artifacts.n1_g1_identical()` that is passed into `geometry.voronoi_skeleton()`. Should we leave that in there commented out or go ahead and dump it?

Also:
* [here](https://github.com/uscuni/sgeop/blob/2a5d6eba1f560c7dec36e0fbbfa91655c31cb086/sgeop/artifacts.py#L446)
* [here](https://github.com/uscuni/sgeop/blob/2a5d6eba1f560c7dec36e0fbbfa91655c31cb086/sgeop/artifacts.py#L500)
* [here](https://github.com/uscuni/sgeop/blob/2a5d6eba1f560c7dec36e0fbbfa91655c31cb086/sgeop/artifacts.py#L564)
* [here](https://github.com/uscuni/sgeop/blob/2a5d6eba1f560c7dec36e0fbbfa91655c31cb086/sgeop/artifacts.py#L909)
* [here](https://github.com/uscuni/sgeop/blob/2a5d6eba1f560c7dec36e0fbbfa91655c31cb086/sgeop/artifacts.py#L929)

**Comment by martinfleis** [comment]
If it is commented out than it means that it was an attempt to solve some problem which is not needed in this version of the code and can be removed.
