### ISSUE TITLE
optional keyword in `simplify_network()` to raise instead of warn

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#121]
I am curious if there is interest in an optional keyword from [`simplify_network()`]() that would cascade into [`simplify_singletons()`](https://github.com/uscuni/sgeop/blob/b5db0feb007f213438b31af218f574f8a6285b1b/sgeop/simplify.py#L31) that would raise exceptions instead of [throwing a warnings](https://github.com/uscuni/sgeop/blob/b5db0feb007f213438b31af218f574f8a6285b1b/sgeop/simplify.py#L194-L199). This would help immensely in debugging & development – see [here](https://github.com/uscuni/sgeop/issues/11#issuecomment-2510419897).

Something like `debug: bool = False` by default. Very open to any other naming if there is interest.

cc @martinfleis

**Comment by martinfleis** [comment]
I would not expose it to a user but you could do a global flag you can set for debugging?
