### ISSUE TITLE
Typing tests

### ISSUE THREAD

**Issue by martinfleis** [uscuni/sgeop#131]
@jGaboardi shall we include some mypy or pyright testing in CI given the amount of type hints you are adding?

**Comment by jGaboardi** [comment]
Potentially.

**Comment by jGaboardi** [comment]
That would basically be mirroring [what's happening](https://github.com/pysal/momepy/blob/main/.github/workflows/mypy.yml) over in `momepy`, right?

**Comment by martinfleis** [comment]
Likely, yes.
