### ISSUE TITLE
public objects in `geometry.py`?

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#23]
Should [`geometry._is_within()`](https://github.com/uscuni/sgeop/blob/4b6dc2361653a9720666bcd37cd2a68d390f9230/sgeop/geometry.py#L18) and [`geometry. voronoi_skeleton()`](https://github.com/uscuni/sgeop/blob/4b6dc2361653a9720666bcd37cd2a68d390f9230/sgeop/geometry.py#L15) really be listed a public functions? I think probably not since it seems that are only used with `artifacts.py`.

**Comment by martinfleis** [comment]
No, neither should be public. I didn't really think about that when writing those.
