### ISSUE TITLE
explanation of keywords in `geometry.voronoi_skeleton()`?

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#25]
Within [`geometry.voronoi_skeleton()`](https://github.com/uscuni/sgeop/blob/199f20cc44a391b76f1ff0376bcec8681d0d7117/sgeop/geometry.py#L99) there is some mismatch between the declared keywords and their explanations in the docstrings.

* `max_segment_length`
  * is this equivalent to `distance` or `limit_distance` in the docstring?
* `secondary_snap_to`
  * This basically a safety net of `snap_to` if declared, right? (see [here](https://github.com/uscuni/sgeop/blob/199f20cc44a391b76f1ff0376bcec8681d0d7117/sgeop/geometry.py#L308))

**Comment by martinfleis** [comment]
I'll fix that :)

**Comment by jGaboardi** [comment]
I'm going to start a PR, that adds some granular tests for `voronoi_skeleton()`. Do you just want to push the updates to that?

**Comment by jGaboardi** [comment]
@martinfleis 

Can I get a 1-liner explanation for the [`limit_distance`](https://github.com/uscuni/sgeop/blob/89f6f8bd32a0b624e5355a50a6f4e4df8b7387d2/sgeop/geometry.py#L127-L128) keyword in `voronoi_skeleton`? If you give me that here I will finish out the docstring.

**Comment by martinfleis** [comment]
It is probably not the best name for what it does. We generate the Voronoi linework and then clip it to fit inside the polygon. To ensure we get a space to make proper topological connections from the linework to the actual points on the edge of the polygon, I am doing the clipping using a polygon with a negative buffer of `limit_distance` or the radius of maximum inscribed circle, whichever is smaller https://github.com/uscuni/sgeop/blob/89f6f8bd32a0b624e5355a50a6f4e4df8b7387d2/sgeop/geometry.py#L172-L177

**Comment by jGaboardi** [comment]
So do we maybe want to update that argument name (something like `clip_limit`?) or keep it named how it is? Either way, I will update the explanation in the docstring in a follow-up PR.

**Comment by martinfleis** [comment]
I don't really mind if you change the name :)
