### ISSUE TITLE
buffer value in `geometry.voronoi_skeleton()`

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#26]
I'm curious if the following could be `(buffer is None) or (buffer == 0):`, or if cases have cropped up where a `buffer=0` is truly the desired parameter?

https://github.com/uscuni/sgeop/blob/199f20cc44a391b76f1ff0376bcec8681d0d7117/sgeop/geometry.py#L133-L134

xref #25

**Comment by martinfleis** [comment]
I don't think should. If a user wants 0 for whatever reason, I'd let them do that.

**Comment by jGaboardi** [comment]
Decision to leave as is.
