### ISSUE TITLE
Add contributing guidelines document

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#4]
Add contributing guidelines document

**Comment by jGaboardi** [comment]
xref: https://github.com/uscuni/sgeop/pull/44#issuecomment-2417197263

Should our contributing guidelines:

* [ ] (a) go in the `README.md`
* [ ] (b) go in a `CONTRIBUTING.md`
* [ ] (c) go in both
* [ ] (d) go somewhere else?

I think probably (c), but what's yall's thoughts @anastassiavybornova @martinfleis ?

**Comment by martinfleis** [comment]
I have two reasons for that. One is that I see ReadMe and contributing guide as document for different audience, where Readme is part of the user-facing documentation (hence no A). And second is that I dislike having the same information at two places at the same time as they will inevitably get out of sync in time (hence no C).

**Comment by anastassiavybornova** [comment]
Agree with (b)! (and it will be linked in the `README` so no need for (c) )
