### ISSUE TITLE
need to return `coins` in `continuity.continuity()`?

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#49]
In both[^1][^2] places where `continuity.continuity()` is called, the [returned `coins`](https://github.com/uscuni/sgeop/blob/89f6f8bd32a0b624e5355a50a6f4e4df8b7387d2/sgeop/continuity.py#L36) value is being ignored. I think returning the `roads, coins` tuple was perhaps an initial attempt and we can now stick to only returning `roads`?

[^1]: [`simplify.py#L60`](https://github.com/uscuni/sgeop/blob/89f6f8bd32a0b624e5355a50a6f4e4df8b7387d2/sgeop/simplify.py#L60)
[^2]: [`simplify.py#L261`](https://github.com/uscuni/sgeop/blob/89f6f8bd32a0b624e5355a50a6f4e4df8b7387d2/sgeop/simplify.py#L261)

**Comment by martinfleis** [comment]
It was very useful for debugging purposes :). I don't think we need to return it in practice.

**Comment by jGaboardi** [comment]
> It was very useful for debugging purposes :). I don't think we need to return it in practice.

This is good to know, and could be useful in the future for better testing & debugging. I think we should keep it for now, but I will include a note in the `continuity.continuity()` docstring pointeing to this issue for explanation.
