### ISSUE TITLE
 expected output from `nodes.get_components()` when `ignore`?

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#56]
I want to confirm expected output with `nodes.get_components()` when using the `ignore` keyword.

https://github.com/uscuni/sgeop/blob/33104e84ff1866f1522540e159ecbf1ee5cce5be/sgeop/nodes.py#L85

```python
In [1]: import geopandas, shapely, sgeop
   ...: 
   ...: p1, p2, p3 = shapely.Point(1,1), shapely.Point(2,2), shapely.Point(3,3)
   ...: 
   ...: line_1_2 = shapely.LineString((p1, p2))
   ...: line_2_3 = shapely.LineString((p2, p3))
   ...: 
   ...: print(sgeop.nodes.get_components([line_1_2, line_2_3]))
   ...: print(sgeop.nodes.get_components([line_1_2, line_2_3], ignore=geopandas.GeoSeries([p2])))
[0 0]
[2. 3.]
```

I would think, intuition would be for the second output to be `[0. 1.]`. I am sure there is a reason we the `[2. 3.]` output, but I am not sure what it is. Maybe something later with artifact identification?

**Comment by martinfleis** [comment]
This is expected. I need labels of connected components. But when there is a node we need to retain, that needs to split the component in two. The easiest way of doing so is to drop that node from graph creation. That way `line_1_2` and `line_2_3` are not seen as neigbbors as they no longer have a point in common and their component labels are different. If I keep the node there, they are connected via this component and have the same component label. 

If it is 0, 1 or 2, 3 does not matter much in practice. The reason this shows up here is that the graph is based only on stuff that has a potential to form a component and to ensure that we get labels for everything, we fill the missing values with a rande starting from max label value + 1. so 0, 1 becomes 2, 3. Expected.

**Comment by jGaboardi** [comment]
Great explanation!
