### ISSUE TITLE
current loop logic breaks topology in certain scenarios

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#69]
Within:

* `nodes.induce_nodes()`
* `nodes.remove_false_nodes()`

***see [below](https://github.com/uscuni/sgeop/issues/69#issuecomment-2443010262)***

-----------------------

Putting this here from Discord:

> *may* have found a bug in [fix_topology()](https://github.com/uscuni/sgeop/blob/681bc5e7d3403098a884dac7d399551e7e6f6a1d/sgeop/nodes.py#L260) whereby if already fixed stuff is passed in, something happens inside that "un-fixes" it.

```python
import geopandas, shapely, sgeop

p10 = shapely.Point(1,0)
p30 = shapely.Point(3,0)
p50 = shapely.Point(5,0)
p21 = shapely.Point(2,1)
p32 = shapely.Point(3,2)
p41 = shapely.Point(4,1)

line1030 = shapely.LineString((p10, p30))
line3050 = shapely.LineString((p30, p50))
line3041323130 = shapely.LineString((p30, p41, p32, p21, p30))

# input "roads" that already meet out simplified critera
frame = geopandas.GeoDataFrame(geometry=[line1030, line3050, line3041323130])
frame
```
```
                               geometry
0                 LINESTRING (1 0, 3 0)
1                 LINESTRING (3 0, 5 0)
2  LINESTRING (3 0, 4 1, 3 2, 2 1, 3 0)
```

![Screenshot 2024-10-27 at 2 54 58 PM](https://github.com/user-attachments/assets/f024854e-8591-4838-b207-2c29e447d28c)

```python
fixed_topology = sgeop.nodes.fix_topology(frame)
fixed_topology
```

```
                                 geometry
0.0            LINESTRING (1 0, 3 0, 5 0)
3.0  LINESTRING (3 0, 4 1, 3 2, 2 1, 3 0)
```
![Screenshot 2024-10-27 at 2 57 38 PM](https://github.com/user-attachments/assets/465f360d-d529-40e7-9917-c47d32ffe191)

------------------------------

xref #68

**Comment by jGaboardi** [comment]
* I have discovered 2 rough edges in `fix_topology()` (actual 1 in `induce_nodes()` and 1 in `remove_false_nodes()` *within* `fix_topology()`) that can lead to improper identification of loop endpoints that in turn can lead to incorrect topology. Both fixes are currently in the [`GH20_nodes_tests_fix_topology`](https://github.com/uscuni/sgeop/tree/GH20_nodes_tests_fix_topology) and tests are passing locally (macOS 14). 
* [CI suite failing](https://github.com/uscuni/sgeop/actions/runs/11565715966) on 5/6 FUA, seemingly with only very minor differences.
* Relavent chunks for the fixes [here](https://github.com/uscuni/sgeop/blob/b198b1f07a2d3d15e472448e3069619356921f99/sgeop/nodes.py#L323-L334) in `induce_nodes()` and [here](https://github.com/uscuni/sgeop/blob/b198b1f07a2d3d15e472448e3069619356921f99/sgeop/nodes.py#L243-L254) in `remove_false_nodes()`.
* Still need to add tests
* I can either roll this stuff into [#67](https://github.com/uscuni/sgeop/pull/67) or make a fresh PR for it once [#67](https://github.com/uscuni/sgeop/pull/67) is merged.

**Comment by martinfleis** [comment]
I'd keep this separately from #67
