### ISSUE TITLE
potential testing schema

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#7]
#### potential testing schema

*this may be tricky to implement*

@martinfleis discussed a potential testing schema would compare known simplified data from a curated parquet to CI results. lf CI fails due the updates being "more correct" than the results in the known parquet, we update the known parquet

**Comment by jGaboardi** [comment]
* This workflow is demoed in https://github.com/uscuni/sgeop/pull/44#issuecomment-2417197263
* @martinfleis I think we can close this issue out and implement to procedure?

**Comment by jGaboardi** [comment]
Also, should we codify this process, maybe in the `README.md` or some contributing guidelines?

xref #4

**Comment by martinfleis** [comment]
Yeah, we should.
