### ISSUE TITLE
should `nodes._status()` never return `'new'`?

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#83]
I find it odd that [this line in `nodes._status()`](https://github.com/uscuni/sgeop/blob/1be6b44b1a06d52453ecbaee205ae649101c4ea4/sgeop/nodes.py#L82) is [never hit during CI](https://github.com/uscuni/sgeop/actions/runs/11751425348/job/32741427970#step:6:295), even considering the 6 full FUA tests.  Is this something to be concerned about or am I simply not understanding? Or maybe it's a failsafe?

**Comment by martinfleis** [comment]
It is there just to be safe. It would be hit if we create a new line and in a subsequent step extend it which is not what normally happens. All the new bits are caught likely by the first `if`.

**Comment by jGaboardi** [comment]
OK. Good info. I am going to document this within the function itself.
