### ISSUE TITLE
try adding Python 3.13 to testing matrix

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#88]
* try adding Python 3.13 to testing matrix
  * `latest`
  * `dev`

**Comment by jGaboardi** [comment]
@martinfleis do we want to keep testing for `macOS{13,14,15}` or drop the testing for `macOS14` and keep `macOS{13,15}`?

I think keeping all is not a bad idea. Thoughts?

**Comment by martinfleis** [comment]
Both ubuntu and windows are tested only on latest. So I'd pick the latest Apple Silicon and the latest Intel chip only. Whichever it is.
