### ISSUE TITLE
`nodes._status()` -- `'new'` in `pandas.Series` always False due to evaluation

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/sgeop#93]
Following #83 (and @martinfleis's explanation [there](https://github.com/uscuni/sgeop/issues/83#issuecomment-2478687401)) I want to triple check the correctness of [the `'new' in ...` condition](https://github.com/uscuni/sgeop/blob/86352bfe585950ef3f98a879809124390d6c87ff/sgeop/nodes.py#L81) in `nodes._status()`. Currently this will never evaluate to `True` since it is passed in as a `pandas.Series`:

```python
import pandas, sgeop

# this should print `new` but does not
print(sgeop.nodes._status(pandas.Series(["one", "new", "two"])))
# "changed"

# due to how `pandas.Series` is evaluated
print("new" in pandas.Series(["one", "new", "two"]))
# False

# so we need to evaluate the values of the Series
print("new" in pandas.Series(["one", "new", "two"]).values)
# True
```

For the small test case of Apalachicola, FL the results of `'_status'` change as follows:

current `main` -- `'new' in x`:
```
.["_status"].value_counts()
# original    549
# changed     125
# new          95
# Name: count, dtype: int64
```

updated condition -- `'new' in x.values`:
```
.["_status"].value_counts()
# original    549
# new         209
# changed      11
# Name: count, dtype: int64
```

This of course affects the full scale [FUA testing for `'_status'` labeling](https://github.com/uscuni/sgeop/actions/runs/11884505311/job/33112782684).

xref:
* #92 

--------------------------

The plot here highlights the difference where:
* thinnest black lines are the original input
* medium lines are the updated conditions
* thickest lines are the original conditions

![_status_comparison](https://github.com/user-attachments/assets/43c261cc-7b99-49a6-afea-05ee39e5c1e7)

It does appear that the results from the original condition are the most correct where lines that are extended are not marked as entirely new. So I am pretty sure our current implementation is accurate, but we should be absolutely sure.

------------------

Data:
* [gh93_status_comparison.zip](https://github.com/user-attachments/files/17792287/gh93_status_comparison.zip)

**Comment by martinfleis** [comment]
How come the sum of value counts above is different?

**Comment by jGaboardi** [comment]
> How come the sum of value counts above is different?

```python
In [1]: (549 + 125 + 95) == (549 + 209 + 11)
Out[1]: True

In [2]: (549 + 125 + 95)
Out[2]: 769

In [3]: (549 + 209 + 11)
Out[3]: 769
```

They are equivalent, no?

**Comment by jGaboardi** [comment]
So if `x` is passed in as a `list` then [the condition](https://github.com/uscuni/sgeop/blob/86352bfe585950ef3f98a879809124390d6c87ff/sgeop/nodes.py#L81) can potentially evaluate as `True` (otherwise the condition will always evaluate to `False` no matter if `'new'` is present). But after combing through the code base I am not finding anywhere we are doing that. @martinfleis Any more thoughts off the top of your head here?

While this does not have a direct impact on geometries being generated, it does have a meaningful impact on geometry labeling, which then could affect the algorithm (from my understanding).

I'd say we need to figure this out before I continue with testing/refactor and [transfer functionality to `simplification.core`](https://github.com/uscuni/simplification/issues/177).

**Comment by martinfleis** [comment]
No idea...

**Comment by jGaboardi** [comment]
> But after combing through the code base I am not finding anywhere we are doing that.

Confirmed programmatically there are no instances of passing in a `list`

**Comment by jGaboardi** [comment]
So I guess we need to determine if our logic of "new" vs. "changed" is sound. [Currently](https://github.com/uscuni/sgeop/blob/86352bfe585950ef3f98a879809124390d6c87ff/sgeop/nodes.py#L77C1-L86C21):

```python
def _status(x: pd.Series) -> str:
    """Determine the status of edge line(s)."""
    if len(x) == 1:
        return x.iloc[0]
    if "new" in x:
        # This logic is here just to be safe. It will be hit if we create a new line
        # and in a subsequent step extend it which is not what normally happens.
        # All the new bits are caught likely by the first ``if``.
        return "new"
    return "changed"
```

... a linestring geometry is considered "new" only `if len(x) == 1` and "new" is that value. Since the [second conditional is flawed](https://github.com/uscuni/sgeop/issues/93#issuecomment-2485990920).

So:
* Is a line "new" if partially new or entirely new?
* I think "new" only if entirely new, elsewise "changed".
* Therefore, I think our current labeling is correct and we can simply remove that final conditional

@martinfleis @anastassiavybornova Do yall concur with this logic?
